Branch new delete command
AY2122S2-CS2113-F12-2/tp pull request #119
Opened 2022-04-05 17:23 UTC by yuhaochua

Add assertion in DeleteCommand#prepareDelete() and JUnit tests for DeleteCommand. It is now ensured that users can only delete an equipment by specifying serial number and show relevant error messages if anything other attributes are provided.

2022-04-06 07:39 UTC, shunyao643 requested changes
Thanks for putting in the assertions! Only some minor changes requested.

2022-04-06 07:39 UTC, shunyao643 commented on src/main/java/seedu/command/DeleteCommand.java
> +            }
You might need to adjust this based on the logic in the other comment further down.

2022-04-06 07:39 UTC, shunyao643 commented on src/main/java/seedu/command/DeleteCommand.java
> +        return "";
Line 83 is unreachable if you assert that `argType.equals("s")` in line 79. I do think the assertion is a good idea though, so maybe you'd like to just go directly to `return argValue` after line 79?

2022-04-06 07:39 UTC, shunyao643 commented on src/test/java/seedu/command/DeleteCommandTest.java
> +                new CommandResult("Only serial number accepted for deleting equipment");
Want to use the `ONLY_SN_ACCEPTED` string in `DeleteCommand` you previously defined?

2022-04-07 09:02 UTC, yuhaochua commented on src/test/java/seedu/command/DeleteCommandTest.java
> +                new CommandResult("Only serial number accepted for deleting equipment");
Okay, will change this to `ONLY_SN_ACCEPTED`!

2022-04-07 09:18 UTC, yuhaochua commented on src/main/java/seedu/command/DeleteCommand.java
> +        return "";
Yes that makes sense, will make the changes accordingly.

2022-04-07 13:55 UTC, shunyao643 approved these changes
LGTM!

2022-04-07 13:55 UTC, merged