Pair update
AY2122S2-CS2113-F12-2/tp pull request #63
Opened 2022-03-22 15:49 UTC by shunyao643

Not super confident of this, have modified the Test classes to use `Pair<String, ?>` instead of `Pair<String, String>`, but I'd like someone else to double check that what I have so far is in line with the Commands and EquipmentManager side implementation, especially with regard to edge cases.

2022-03-23 16:01 UTC, yuhaochua requested changes
I think the general idea is down! But might have to make some changes to fully realise the initial purpose of using Pair<String, ?>

2022-03-23 16:01 UTC, yuhaochua commented on src/main/java/seedu/command/UpdateCommand.java
> +        ArrayList<Pair<String, ?>> pairs = new ArrayList<>();
I think if the point of using this Pair<String, ?> was to allow us to put the equipmentType and cost as EquipmentType and Double objects respectively, then we will need to change ModificationCommand too? We will have to declare those attributes as their respective classes right?

2022-03-23 16:01 UTC, yuhaochua commented on src/main/java/seedu/equipment/EquipmentManager.java
> +                    updatedEquipment.setType(EquipmentType.valueOf((String)updates.getValue()));
Why are we type casting this as string, if the point of the Pair<String, ?> was to enable us to put the EquipmentType class object directly into the Pair?

2022-03-23 16:01 UTC, yuhaochua commented on src/main/java/seedu/equipment/EquipmentManager.java
> +                updatedEquipment.setCost(Double.valueOf((String) updates.getValue()));
Same as above, but this one is Double.

2022-03-23 16:53 UTC, shunyao643 commented on src/main/java/seedu/equipment/EquipmentManager.java
> +                    updatedEquipment.setType(EquipmentType.valueOf((String)updates.getValue()));
It's very strange: I need to explicitly cast it to be a `String` so that it can then be converted to `EquipmentType`. I haven't managed to found a better workaround than this!

2022-03-23 16:54 UTC, shunyao643 commented on src/main/java/seedu/command/UpdateCommand.java
> +        ArrayList<Pair<String, ?>> pairs = new ArrayList<>();
Yeah, the first String is the key identifier right? The second one is a wildcard so it can support any type, including Double and EquipmentType.

2022-03-23 17:03 UTC, yuhaochua commented on src/main/java/seedu/equipment/EquipmentManager.java
> +                    updatedEquipment.setType(EquipmentType.valueOf((String)updates.getValue()));
I think if the value that we are getting here from `updates.getValue()` has class of `EquipmentType`, then we do not need to convert it anymore? We can directly pass it into `updatedEquipment.setType` probably.

2022-03-24 07:16 UTC, Bryan-BC approved these changes
Just need some minor updates but nothing crucial. Nonetheless, LGTM!

2022-03-24 07:16 UTC, Bryan-BC commented on src/main/java/seedu/equipment/EquipmentManager.java
> +                    updatedEquipment.setType(EquipmentType.valueOf((String)updates.getValue()));
Same comment for this one is it possible to implement without the casting?

2022-03-25 10:41 UTC, yuhaochua approved these changes
LGTM!

2022-03-25 10:44 UTC, merged

2022-03-25 13:15 UTC, shunyao643 commented
closes #51